# Generated by Erlang.mk. Edit at your own risk!

src/rabbit_api2_app.erl:: include/rabbit_api2.hrl; @touch $@
src/rabbit_api2_config.erl:: include/rabbit_api2.hrl; @touch $@
src/rabbit_api2_sup.erl:: include/rabbit_api2.hrl; @touch $@
src/rabbit_api2_worker.erl:: include/rabbit_api2.hrl; @touch $@

COMPILE_FIRST +=
